
vich_uploader:
    db_driver: orm

    mappings:
        concert_images:
            uri_prefix: /images/concertsUpload
            upload_destination: '%kernel.project_dir%/public/images/concertsUpload'
